language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: adyshev
  password:
    secure: p7eqVYx8qKzZn+8JfzkQuU3zsc5Z2vhawz0nxixHsOA05ELCeUguW25FHD//J/I3TBiaR40SB8ReuNGGHk/HocWxk4duq+Vc6wGQUiNppvFnEPro0D17mPYV9ZG1QS3LD+ro+Q0zyCT4wiC++geD0Guo+r6rLpCDcHuQhYa3Yyh2E4rk0OXv7l21hND5RrHLlqS5AVsa0OHLmuMKGEnx7fcChNnIEZ9y6qcMM0kWo2hCqRQIJ1aYbP9R6H61JYu2Mq3zaoUKU7lDQ2bsXWhIeF6y0/oKxIAQftxMxK6u/LJ46Vu6bVx8gMfAHpkFlnGAzjEZOxvE3EJt6OziNl9ooREK/RSGKsQyU9urks3c+L7EPwnYUCe2ryUNva82YyXPTOIvTTQ5s4pNSD1VNA9xdB9YIOXQeZ4zc2hiFK+fWvLGJmfhPY75z7D8SHqpvOsaVuTZkR0THdjPYIgx6ftLeTXSFE8H/wuW3IVbLta7nslq8A6/SYnEicDvfMqe0B1ax4PzbSRVJ7Y5+z1njBdXY7ENAhNG6L4pr2ErAacU3pRkab2j0CYsRoEWI50RjrJfXzPduzWtMgosrF0KUcumuAnrFcSX2ERYzQRS9KoFx5Vy4FIH6/Kw7NzSu8V6REw3cap6UJMf3tA92DOMFrdKCMY0gV061mbiskhHMoGeaUY=
  on:
    tags: true
    repo: adyshev/eventbus
    python: 3.8
