language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    secure: f7nChWI/UENeDg729arv9dsjDSc0t7+bS+3bbMYcDPEqIaUCTgca0NIhJfqcJzaT9xjc+AijaBDSJciOPTnksYOPCg9Jt3PsC7fK1Xva3N7ebNEPQpMcvxYetvJTccGVBma21SvZj/3j1GIlEqXfLyTn732zSvuqiIsof9MgQYj7NItuLNt0HCrAoQaiOIruluDEQpOQEYo6gDWNOYAxh7sYcvZoyvOlRc2ehjYTFZcDQzFIX6fv63ds6utWY/CjnDaHfbtjNvptrqKOXURETWXe5/CATX+nK6PM/AgFsXUDYBa36vC3whfDq5yQcoHWd9OsxB4iri7vBPaXATZzAF58UlKY7FCI6TPP+UTSKs95hq7n6UVnX8fHbLugJzDitpQdAhYe3waPUwLEDP4N+zlBhSmuEYXxVDGObJWqt69UPBKIOz/k1Wubkd0VsaqEHdQr4hll8UfWIJRcwoLhk9TQSvXRhYudgQ6I80j6t6GdeWaWoVXsUwni+cFv4Jjpyte+gLP4Ap+uOjrHdmB5tyz3UjoGPWJ7DkRdd4MOtC+eaQIXByl843JhoWzE1CLx1JZ0XfSq2f+qK0CeFohx1rN+ohrAcDxrzGpHuEsmxscMjvhitARk0d1igzM2cdJ5Uzaj3+lCM/qWbZaQwrJUrQkxMVepBmwoP0tLuguHG8Y=
  on:
    tags: true
    repo: adyshev/eventbus
    python: 3.8
